### ISSUE TITLE
Default credentials not working

### ISSUE THREAD

**Issue by jmorgade** [xoseperez/the-things-stack-docker#1]
Hi, 

I'm testing tag v1.1.6 on a **raspberry pi 3 B** using balena cloud.

I needed to fall back to 1.1.6 since official TTS release 1.1.7 provided at balena cloud did not rise properly (at least with default image settings)

`<stack> exec ./entrypoint.sh: exec format error
Restarting service 'stack sha256:530410857866c28ef69e5eb539c1bb46e39c6b9545cbe47594d0de7cfa54231c'
Service exited 'stack sha256:530410857866c28ef69e5eb539c1bb46e39c6b9545cbe47594d0de7cfa54231c'
`

After deploying tag v1.1.6, I am at least able to desploy postgres, redis and stack services and can rearch the TTS console and can see the login page (https://<my raspberry pi IP address>) . However, default credentials "admin" "changeme" report back pkg/web/oauthclient:exchange

`
{
  "code": 7,
  "message": "error:pkg/web/oauthclient:exchange (token exchange refused)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/web/oauthclient",
      "name": "exchange",
      "message_format": "token exchange refused",
      "correlation_id": "3dbb243913d946fca38c4e25a5043342",
      "cause": {
        "namespace": "pkg/errors",
        "name": "net_dns",
        "message_format": "{message}",
        "attributes": {
          "message": "lookup lns.example.com on 127.0.0.11:53: server misbehaving",
          "not_found": false,
          "timeout": false
        },
        "correlation_id": "366822a628e54001b00d6659db602c56",
        "code": 14
      },
      "code": 7
    }
  ]
}
`

I tried no secure access and default credentials seem not to work either. 

The remote machine I am using to reach rapsberry Pi is placed on the same subnet so I am wondering if I am really missing something beyond default settings addressed in the documentation (I already tried setting TTS_DOMAIN with the RPI ip address)

**Comment by xoseperez** [comment]
Hi @jmorgade 
The error usually means the certificate does not match the domain name and indeed looks like you have the default "lns.example.com" in the TTS_DOMAIN. But since you said you already tried the RPi IP address... my suggestions are: 1) make sure your RPi IP address is static and 2) reset the credentials using the rset script (see https://github.com/xoseperez/the-things-stack-docker#resetting-values).

**Comment by jmorgade** [comment]
Hello @xoseperez 

Sorry, my bad, you absolutely right.  I though I was properly setting up the TTS_DOMAIN address but I finally notice I wasn't. I misunderstood a bit the guidelines there.  I can confirm that overriding the TTS_DOMAIN with device IP address, it works.
