### ISSUE TITLE
Docker-compose.yml missing line 

### ISSUE THREAD

**Issue by nor24o** [xoseperez/the-things-stack-docker#4]
I think this is missing from the start of the docker file file because without it I  can't push .
" version: '2' "

**Comment by xoseperez** [comment]
Compose doesn't use the version tag and it has flagged it as obsolete in the latest versions. Balena is based on an older version hence it fails to push without it. 

I have added it back but I guess it will eventually disappear in the future.

https://docs.docker.com/compose/compose-file/04-version-and-name/
